# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b4c6cf2f35773c6192ea9f38ce6147099a61a2d6639447c89aafb6a95308ba4f35846f2d605d606441155de39bfd6aaa98e3be9683f54ceaa65e72b220d86fcf

test:
  secret_key_base: c0e6e33967f6eb63e06f7914bf26b058666a167f093bbd93e259d525710d863517c084a6982c9c2e10c76f7fdc903f9d0401a07b7becb1e4a2b5610b08d73624

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
